# Generated by Django 4.2.8 on 2023-12-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Место')),
                ('description_short', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('description_long', models.TextField(blank=True, null=True, verbose_name='Длинное описание')),
                ('coordinates', models.JSONField(blank=True, null=True, verbose_name='Координаты')),
            ],
        ),
    ]
