# Generated by Django 4.2.8 on 2023-12-24 10:25

from django.db import migrations
import json
import os


def create_2_places(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    directory = 'static/places'
    for json_file in os.listdir(directory):
        with open(os.path.join(directory, json_file)) as file:
            json_place = json.load(file)
        Place.objects.create(
            title=json_place['title'],
            description_short=json_place['description_short'],
            description_long=json_place['description_long'],
            coordinates=json_place['coordinates']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_2_places)
    ]
