# Generated by Django 4.2.8 on 2023-12-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_image_link_image_picture_alter_image_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на картинку'),
        ),
    ]
