# Generated by Django 4.2.8 on 2023-12-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
