# Generated by Django 4.2.8 on 2023-12-29 12:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_options_alter_image_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Длинное описание'),
        ),
    ]
