# Generated by Django 4.2.8 on 2024-01-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_image_picture_alter_image_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Номер'),
        ),
    ]
